name: Deploy to Private EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::684210808108:role/github-actions-ROLE
          aws-region: ap-south-1

      - name: Check AWS identity
        run: |
          aws sts get-caller-identity    

      - name: Deploy using SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0e9c6d52b44180434 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /var/www/html", 
              "if [ -d .git ]; then sudo git pull origin main; else sudo git clone https://github.com/Thiru-pathi/private-ec2-connect-project-01.git /var/www/html; fi", 
              "sudo chown -R nginx:ngin /var/www/html",
              "sudo systemctl reload nginx", "echo Deployment completed"
            ]'
